sudo: required
services:
    - docker

before_install:
    - docker build -t drake666/react-client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true drake666/react-client npm test

after_success:
    - docker build -t drake666/multi-client ./client
    - docker build -t drake666/multi-nginx ./nginx
    - docker build -t drake666/multi-server ./server
    - docker build -t drake666/multi-worker ./worker
    # Log in to dockerhub
    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images
    - docker push drake666/multi-client
    - docker push drake666/multi-nginx
    - docker push drake666/multi-server
    - docker push drake666/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-935276115586
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY